<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.010"/>
    <xacro:property name="camera_width" value="0.03"/>
    <xacro:property name="camera_height" value="0.03"/>
    <xacro:property name="camera_mass" value="0.3"/>


    <!-- CAMERA LINK-->
     <link name="camera_link">
        <visual>
            <origin xyz="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <material name="black"/>            
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>    
            <origin xyz="0.0 0.0 0.0"/>
        </collision>
        <xacro:inertial_box mass="${camera_mass}" x="${camera_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
     </link>

    <!-- OPTICAL LINK -->
    <!-- <link name="camera_link_optical">
    
    </link> -->

    <!-- CAMERA JOINT -->
    <joint name="camera_joint" type="fixed">
        <parent link="chassis"/>
        <child link="camera_link"/>
        <origin xyz="${chassis_length+0.01} 0.0 ${chassis_height /2}" rpy="0.0 0.0 0.0"/>
        
    </joint>
     

</robot>