<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <!-- Add the inertial macros file here. -->
    <xacro:include filename="inertials_macros.xacro"/>

    <!-- Declare urdf properties here.-->

    <xacro:property name="chassis_length" value="1.6"/>
    <xacro:property name="chassis_width" value="0.9"/>
    <xacro:property name="chassis_height" value="0.35"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.51"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="wheel_radius" value="0.2"/>
    <xacro:property name="wheel_thickness" value="0.12"/>
    <xacro:property name="chassis_mass" value="500"/>
    <xacro:property name="lift_link_mass" value="150"/>
    <xacro:property name="castor_wheel_mass" value="20"/>
    <xacro:property name="wheel_mass" value="40"/>
    <xacro:property name="caster_wheel_radius" value="0.10"/>
    <xacro:property name="caster_wheel_mass" value="20"/>
    <xacro:property name="caster_wheel_offset_x" value="1.4"/>
    <xacro:property name="caster_wheel_offset_z" value="-0.091"/>
    <xacro:property name="lift_length" value="1.4"/>
    <xacro:property name="lift_width" value="0.8"/>
    <xacro:property name="lift_height" value="0.1"/>
    <xacro:property name="lift_max_height" value="1.2"/>


    <!-- Define materials here.-->
    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->
    <link name="base_link">
    </link>


    <!-- BASE FOOTPRINT LINK-->
    <link name="base_footprint">
    </link>

    <!-- CHASSIS LINK -->
    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>    
    </link>

    <!-- LIFT LINK -->
    <link name="lift_link">
        <visual>
            <!-- <origin xyz="${chassis_length/2 - lift_length/2} 0 ${chassis_height + lift_height/2}"/> -->
            <geometry>
                <box size="${lift_length} ${lift_width} ${lift_height}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <!-- <origin xyz="${chassis_length/2 - lift_length/2} 0 ${chassis_height }"/> -->
            <geometry>
                <box size="${lift_length} ${lift_width} ${lift_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${lift_link_mass}" x="${lift_length}" y="${lift_width}" z="${lift_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!-- LEFT WHEEL LINK-->

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>           
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- RIGHT WHEEL LINK -->

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- CASTER WHEEL LINK -->
    
    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>


    <!-- JOINTS -->

    <!-- BASE_FOOTPRINT JOINT-->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- CHASSIS_JOINT-->
    <joint name="chasis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <!-- LIFT JOINT -->
    <joint name="lift_joint" type="prismatic">
        <parent link="chassis"/>
        <child link="lift_link"/>
        <!-- Position at the top of the chassis -->
        <origin xyz="${chassis_length/2} 0 ${chassis_height + lift_height/2}" rpy="0 0 0"/>
        <!-- Vertical movement (z-axis) -->
        <axis xyz="0 0 1"/>
        <limit lower="0.0" upper="${lift_max_height}" effort="5000" velocity="0.2"/>
    </joint>


    <!-- RIGHT_WHEEL_JOINT-->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <!-- LEFT_WHEEL_JOINT-->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <!-- CASTER_WHEEL_JOINT-->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>

</robot>